### ISSUE TITLE
Great fork

### ISSUE THREAD

**Issue by no0bi1** [brandosha/gameplaycolor#7]
The main guy is kind of a bum. This one is awesome, always saves your progress, has cloud backup, and can import/export saves. Just curious what will happen if the server goes down?

**Comment by brandosha** [comment]
I’m glad you appreciated the features :)

The only servers this app relies on are google drive for backup and file access and GitHub for hosting. However, the app works fully offline so even if google and GitHub go down it will still work because everything is saved on your device. The only thing that wouldn’t work is adding new games and backing up the saves.
